//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfTheDay_webservice.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OfTheDayEntities : DbContext
    {
        public OfTheDayEntities()
            : base("name=OfTheDayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Celebrity> Celebrities { get; set; }
        public virtual DbSet<Fittness_Model> Fittness_Models { get; set; }
        public virtual DbSet<Laugh> Laughs { get; set; }
        public virtual DbSet<Meme> Memes { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Video_Clip> Video_Clips { get; set; }
        public virtual DbSet<Word> Words { get; set; }
    }
}
